# Next.js

help:
	@echo USAGE:
	@echo 	make [COMMAND]

	@echo COMMANDS:
	@echo 	help             this help
	@echo 	install          npm install packages, then build frontend
	@echo 	dev              start dev server
	@echo 	build            build frontend
	@echo 	prod             start server (in background)
	@echo 	down             stop server


install:
	@echo "Installing packages..."
	@npm install
	@echo "Building frontend..."
	@npm run build

dev:
	@echo "Starting frontend dev server..."
	@npm run dev

build:
	@echo "Building frontend..."
	@npm run build

prod:
	@echo "Starting server..."
	@npm run start

down:
	@echo "Stopping server..."
	@npm run stop
